services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: db-dev
    restart: always
    environment:
      POSTGRES_DB: klios_teste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
